export const FEATURE_IDS = [
  'screenshot-screen',
  'screenshot-area',
  'screenshot-window',
  'ocr',
  'qrcode',
  'timer-capture',
  'scroll-capture',
  'all-in-one',
  'recording',
  'video-editor',
  'desktop-icons',
  'freeze-screen',
  'display-selector',
  'print',
  'desktop-wallpaper',
  'transcription',
  'capture-sound',
  'color-picker',
] as const;

export type FeatureId = (typeof FEATURE_IDS)[number];

export const PLATFORM_CAPABILITIES = {
  macos: [
    'screenshot-screen',
    'screenshot-area',
    'screenshot-window',
    'ocr',
    'qrcode',
    'timer-capture',
    'scroll-capture',
    'all-in-one',
    'recording',
    'video-editor',
    'desktop-icons',
    'freeze-screen',
    'display-selector',
    'print',
    'desktop-wallpaper',
    'transcription',
    'capture-sound',
    'color-picker',
  ],
  windows: [
    'screenshot-screen',
    'screenshot-area',
    'screenshot-window',
    'ocr',
    'qrcode',
    'timer-capture',
    'scroll-capture',
    'all-in-one',
    'recording',
    'video-editor',
    'desktop-icons',
    'freeze-screen',
    'display-selector',
    'print',
    'desktop-wallpaper',
    'transcription',
    'color-picker',
  ],
  linuxX11: [
    'screenshot-screen',
    'screenshot-area',
    'screenshot-window',
    'qrcode',
    'timer-capture',
    'scroll-capture',
    'all-in-one',
    'recording',
    'video-editor',
    'freeze-screen',
    'display-selector',
    'print',
    'desktop-wallpaper',
    'color-picker',
  ],
  linuxWayland: [
    'screenshot-screen',
    'screenshot-area',
    'qrcode',
    'all-in-one',
    'recording',
    'video-editor',
    'print',
  ],
  headless: [],
} as const satisfies Record<string, readonly FeatureId[]>;

export type CapabilityTarget = keyof typeof PLATFORM_CAPABILITIES;
