export const DAEMON_METHODS = {
  'area-selector': [
    'disableWindowTransitions',
    'hideWindowWithoutTransitions',
    'showWindowWithoutTransitions',
    'setWindowRegion',
    'getForegroundWindow',
    'setForegroundWindow',
  ],
  'camera-preview': ['show', 'hide', 'update', 'setContentProtection'],
  'desktop-helper': ['hide', 'show'],
  'desktop-wallpaper': ['get'],
  'display-selector': ['select', 'cancel'],
  'freeze-screen': ['freeze', 'release', 'prewarm'],
  'media-devices': ['list', 'startMicTest', 'stopMicTest'],
  ocr: ['recognize'],
  print: ['image'],
  qrcode: ['detect'],
  'recording-control': ['listIOSDevices'],
  'recording-overlay': ['show', 'showWindow', 'hide'],
  screenshot: ['capture-area', 'capture-window'],
  'screen-recorder': [
    'start',
    'pause',
    'resume',
    'stop',
    'status',
    'setMicrophone',
    'setSystemAudio',
    'setCamera',
  ],
  'scroll-capture': [
    'start',
    'startAutoScroll',
    'stopAutoScroll',
    'finish',
    'cancel',
  ],
  'timer-control': ['show', 'hide'],
  'window-selector': ['list'],
} as const;
