import type { SettingsItem } from '../settings-registry';
import type { PreviewCorner } from '@/types/settings';

export const GENERAL_ITEMS: SettingsItem[] = [
  {
    id: 'general.startOnLogin',
    category: 'general',
    section: 'Application',
    type: 'switch',
    label: 'Start on login',
    description: 'Launch Capty automatically when you log in',
    keywords: ['startup', 'launch', 'boot', 'login', 'auto start'],
    getValue: s => s.general.startOnLogin,
    setValue: (s, v) => ({
      general: { ...s.general, startOnLogin: v },
    }),
  },
  {
    id: 'general.playSound',
    feature: 'capture-sound',
    category: 'general',
    section: 'Application',
    type: 'switch',
    label: 'Play sound',
    description: 'Play a sound effect when taking screenshots',
    keywords: ['audio', 'sound', 'effect', 'noise', 'capture sound'],
    getValue: s => s.general.playSoundOnScreenshot,
    setValue: (s, v) => ({
      general: { ...s.general, playSoundOnScreenshot: v },
    }),
  },
  {
    id: 'general.showDeletionNotifications',
    category: 'general',
    section: 'Application',
    type: 'switch',
    label: 'Show deletion notifications',
    description:
      'Show a notification when a screenshot or video is permanently deleted',
    keywords: [
      'notification',
      'delete',
      'deletion',
      'remove',
      'screenshot',
      'video',
      'recording',
    ],
    getValue: s => s.general.showDeletionNotifications,
    setValue: (s, v) => ({
      general: { ...s.general, showDeletionNotifications: v },
    }),
  },
  {
    id: 'general.previewCorner',
    category: 'general',
    section: 'Preview',
    type: 'select',
    label: 'Preview corner',
    description:
      'Corner of the screen where capture previews appear and stack up',
    keywords: [
      'preview',
      'corner',
      'position',
      'placement',
      'thumbnail',
      'bottom',
      'top',
      'left',
      'right',
    ],
    options: [
      { value: 'bottom-right', label: 'Bottom right' },
      { value: 'bottom-left', label: 'Bottom left' },
      { value: 'top-right', label: 'Top right' },
      { value: 'top-left', label: 'Top left' },
    ],
    getValue: s => s.preview.corner,
    setValue: (s, v) => ({
      preview: { ...s.preview, corner: v as PreviewCorner },
    }),
  },
  {
    id: 'general.previewAutoDismiss',
    category: 'general',
    section: 'Preview',
    type: 'switch',
    label: 'Dismiss previews automatically',
    description:
      'Hide capture previews after a delay, unless you are hovering or an action is running',
    keywords: [
      'preview',
      'auto',
      'dismiss',
      'hide',
      'close',
      'timeout',
      'duration',
      'disappear',
    ],
    getValue: s => s.preview.autoDismiss,
    setValue: (s, v) => ({
      preview: { ...s.preview, autoDismiss: v },
    }),
  },
  {
    id: 'general.previewAutoDismissSeconds',
    category: 'general',
    section: 'Preview',
    type: 'select',
    label: 'Dismiss after',
    description: 'How long a capture preview stays on screen',
    keywords: [
      'preview',
      'auto',
      'dismiss',
      'delay',
      'seconds',
      'timeout',
      'duration',
      'disappear',
    ],
    options: [
      { value: '3', label: '3 seconds' },
      { value: '5', label: '5 seconds' },
      { value: '10', label: '10 seconds' },
      { value: '15', label: '15 seconds' },
      { value: '30', label: '30 seconds' },
      { value: '60', label: '1 minute' },
    ],
    getValue: s => String(s.preview.autoDismissSeconds),
    setValue: (s, v) => ({
      preview: { ...s.preview, autoDismissSeconds: Number(v) },
    }),
    visibleWhen: s => s.preview.autoDismiss,
  },
  {
    id: 'general.historyEnabled',
    category: 'general',
    section: 'History',
    type: 'switch',
    label: 'Enable history',
    description: 'Keep a history of your screenshots for quick access',
    keywords: ['history', 'recent', 'past', 'log'],
    getValue: s => s.history.enabled,
    setValue: (s, v) => ({
      history: { ...s.history, enabled: v },
    }),
  },
  {
    id: 'general.historyMaxItems',
    category: 'general',
    section: 'History',
    type: 'slider',
    label: 'Maximum items',
    description: 'Number of screenshots to keep in history',
    keywords: ['history', 'limit', 'max', 'count', 'items'],
    min: 10,
    max: 200,
    step: 10,
    getValue: s => s.history.maxItems,
    setValue: (s, v) => ({
      history: { ...s.history, maxItems: v },
    }),
    visibleWhen: s => s.history.enabled,
  },
];
