[workspace]
resolver = "2"
members = ["daemon-common", "daemon-linux", "daemon-win", "app-gpui"]

[workspace.package]
rust-version = "1.93"

[profile.dev]
opt-level = 1
debug = "line-tables-only"

[profile.dev.package."*"]
opt-level = 3
debug = false

[workspace.lints.clippy]
disallowed_methods = "deny"
too_many_arguments = "allow"
type_complexity = "allow"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(feature, values("cargo-clippy"))',
] }

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
