//! Subtitle generation — port of `main/transcription/whisper-transcribe.ts`
//! and `main/utils/whisper.ts`. The same bundled `whisper` CLI and the same
//! `~/.config/poratake/whisper` models are used, so a transcript generated by
//! either shell is the same file. Audio is converted to whisper's 16 kHz mono
//! WAV with Media Foundation rather than FFmpeg, so this shell bundles nothing.

use std::path::{Path, PathBuf};

use crate::video::sidecars::{SubtitleData, SubtitleMeta, SubtitleSegment, SubtitleWord};

/// The whisper.cpp model files, keyed by the id the settings store.
pub fn model_file(model: &str) -> &'static str {
    match model {
        "small" => "ggml-small.bin",
        "medium" => "ggml-medium.bin",
        _ => "ggml-base.bin",
    }
}

/// `getWhisperDir` — the models live next to the shared config.
pub fn whisper_dir() -> PathBuf {
    crate::config::store::config_dir().join("whisper")
}

pub fn model_path(model: &str) -> PathBuf {
    whisper_dir().join(model_file(model))
}

/// `getNativeBinaryPath('whisper')`, resolved from the running executable the
/// same way the daemon binary is.
pub fn cli_path() -> PathBuf {
    const BINARY: &str = if cfg!(windows) {
        "whisper.exe"
    } else {
        "whisper"
    };

    if let Ok(path) = std::env::var("PORATAKE_WHISPER_PATH") {
        let path = PathBuf::from(path);
        if path.exists() {
            return path;
        }
    }

    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            let packaged = dir.join("binaries").join("whisper").join(BINARY);
            if packaged.exists() {
                return packaged;
            }
            for ancestor in dir.ancestors().skip(1) {
                let candidate = ancestor
                    .join("src")
                    .join("main")
                    .join("binaries")
                    .join("whisper")
                    .join(BINARY);
                if candidate.exists() {
                    return candidate;
                }
            }
        }
    }
    PathBuf::from(BINARY)
}

pub fn is_binary_available() -> bool {
    cli_path().is_file()
}

/// `-dtw` takes the model name as its preset.
fn dtw_preset(model: &str) -> &str {
    match model {
        "small" | "medium" => model,
        _ => "base",
    }
}

/// whisper wants 16 kHz mono; the decoder hands back 48 kHz stereo.
pub const WHISPER_SAMPLE_RATE: u32 = 16_000;

/// Downmixes to mono and resamples to 16 kHz by linear interpolation, which is
/// what `-ar 16000 -ac 1` gives.
pub fn to_whisper_pcm(samples: &[i16], source_rate: u32) -> Vec<i16> {
    let frames = samples.len() / 2;
    if frames == 0 || source_rate == 0 {
        return Vec::new();
    }
    let target_frames =
        ((frames as f64) * WHISPER_SAMPLE_RATE as f64 / source_rate as f64).round() as usize;
    let mut mono = Vec::with_capacity(target_frames);

    for index in 0..target_frames {
        let position = index as f64 * source_rate as f64 / WHISPER_SAMPLE_RATE as f64;
        let left_frame = position.floor() as usize;
        let right_frame = (left_frame + 1).min(frames - 1);
        let fraction = position - left_frame as f64;

        let average = |frame: usize| -> f64 {
            let offset = frame * 2;
            (samples[offset] as f64 + samples[offset + 1] as f64) / 2.0
        };
        let value = average(left_frame.min(frames - 1)) * (1.0 - fraction)
            + average(right_frame) * fraction;
        mono.push(value.clamp(i16::MIN as f64, i16::MAX as f64) as i16);
    }
    mono
}

/// A 16-bit mono PCM WAV, the container whisper's `-f` reads.
pub fn wav_bytes(samples: &[i16], sample_rate: u32) -> Vec<u8> {
    let data_len = (samples.len() * 2) as u32;
    let mut bytes = Vec::with_capacity(44 + data_len as usize);
    bytes.extend_from_slice(b"RIFF");
    bytes.extend_from_slice(&(36 + data_len).to_le_bytes());
    bytes.extend_from_slice(b"WAVE");
    bytes.extend_from_slice(b"fmt ");
    bytes.extend_from_slice(&16u32.to_le_bytes());
    bytes.extend_from_slice(&1u16.to_le_bytes()); // PCM
    bytes.extend_from_slice(&1u16.to_le_bytes()); // mono
    bytes.extend_from_slice(&sample_rate.to_le_bytes());
    bytes.extend_from_slice(&(sample_rate * 2).to_le_bytes()); // bytes per second
    bytes.extend_from_slice(&2u16.to_le_bytes()); // block align
    bytes.extend_from_slice(&16u16.to_le_bytes()); // bits per sample
    bytes.extend_from_slice(b"data");
    bytes.extend_from_slice(&data_len.to_le_bytes());
    for sample in samples {
        bytes.extend_from_slice(&sample.to_le_bytes());
    }
    bytes
}

/// `parseWhisperTimestamp` — `HH:MM:SS.mmm`.
pub fn parse_timestamp(value: &str) -> Option<f64> {
    let trimmed = value.trim();
    let (clock, millis) = match trimmed.split_once(['.', ',']) {
        Some((clock, fraction)) => {
            let mut padded = fraction.to_string();
            while padded.len() < 3 {
                padded.push('0');
            }
            (clock, padded[..3].parse::<u32>().ok()?)
        }
        None => (trimmed, 0),
    };

    let parts: Vec<&str> = clock.split(':').collect();
    if parts.len() != 3 {
        return None;
    }
    let hours: u32 = parts[0].parse().ok()?;
    let minutes: u32 = parts[1].parse().ok()?;
    let seconds: u32 = parts[2].parse().ok()?;
    Some(hours as f64 * 3600.0 + minutes as f64 * 60.0 + seconds as f64 + millis as f64 / 1000.0)
}

/// `parseWhisperOutput` — whisper's `-ojf` JSON into subtitle segments.
pub fn parse_output(json: &serde_json::Value) -> Vec<SubtitleSegment> {
    let Some(items) = json.get("transcription").and_then(|value| value.as_array()) else {
        return Vec::new();
    };

    items
        .iter()
        .map(|segment| {
            let offsets = segment.get("offsets");
            let start = offsets
                .and_then(|offsets| offsets.get("from"))
                .and_then(serde_json::Value::as_f64)
                .map(|value| value / 1000.0)
                .or_else(|| {
                    segment
                        .get("timestamps")
                        .and_then(|stamps| stamps.get("from"))
                        .and_then(serde_json::Value::as_str)
                        .and_then(parse_timestamp)
                })
                .unwrap_or(0.0);
            let end = offsets
                .and_then(|offsets| offsets.get("to"))
                .and_then(serde_json::Value::as_f64)
                .map(|value| value / 1000.0)
                .or_else(|| {
                    segment
                        .get("timestamps")
                        .and_then(|stamps| stamps.get("to"))
                        .and_then(serde_json::Value::as_str)
                        .and_then(parse_timestamp)
                })
                .unwrap_or(start);

            SubtitleSegment {
                start,
                end,
                text: segment
                    .get("text")
                    .and_then(serde_json::Value::as_str)
                    .unwrap_or_default()
                    .trim()
                    .to_string(),
                words: parse_tokens(segment.get("tokens"), start, end),
            }
        })
        .collect()
}

/// `parseWhisperTokens` — whisper emits sub-word tokens, which are joined back
/// into words on the leading space each new word carries.
fn parse_tokens(
    tokens: Option<&serde_json::Value>,
    segment_start: f64,
    segment_end: f64,
) -> Option<Vec<SubtitleWord>> {
    let tokens = tokens?.as_array()?;
    if tokens.is_empty() {
        return None;
    }

    struct Parsed {
        text: String,
        has_leading_space: bool,
        start: Option<f64>,
        end: Option<f64>,
    }

    let parsed: Vec<Parsed> = tokens
        .iter()
        .filter_map(|token| {
            let raw = token.get("text").and_then(serde_json::Value::as_str)?;
            // Whisper marks special tokens with brackets; they are not speech.
            if raw.starts_with("[_") || raw.trim().is_empty() {
                return None;
            }
            let offsets = token.get("offsets");
            Some(Parsed {
                text: raw.trim_start().to_string(),
                has_leading_space: raw.starts_with(' '),
                start: offsets
                    .and_then(|offsets| offsets.get("from"))
                    .and_then(serde_json::Value::as_f64)
                    .map(|value| value / 1000.0),
                end: offsets
                    .and_then(|offsets| offsets.get("to"))
                    .and_then(serde_json::Value::as_f64)
                    .map(|value| value / 1000.0),
            })
        })
        .filter(|token| !token.text.is_empty())
        .collect();

    if parsed.is_empty() {
        return None;
    }

    let mut words: Vec<SubtitleWord> = Vec::new();
    let mut current: Option<SubtitleWord> = None;
    for token in parsed {
        let start = token.start.unwrap_or(segment_start).max(segment_start);
        let end = token.end.unwrap_or(segment_end).min(segment_end);
        if end <= start {
            continue;
        }

        match current.as_mut() {
            Some(word) if !token.has_leading_space => {
                word.text.push_str(&token.text);
                word.end = end;
            }
            _ => {
                if let Some(word) = current.take() {
                    words.push(word);
                }
                current = Some(SubtitleWord {
                    text: token.text,
                    start,
                    end,
                });
            }
        }
    }
    if let Some(word) = current.take() {
        words.push(word);
    }

    (!words.is_empty()).then_some(words)
}

/// `HUGGINGFACE_MODEL_BASE` in `main/utils/whisper.ts`.
const MODEL_BASE_URL: &str = "https://huggingface.co/ggerganov/whisper.cpp/resolve/main";

/// Downloads a whisper model into the shared whisper directory. Blocking, so
/// callers run it on the background executor. The download goes to the same
/// public model host the Electron shell uses.
pub fn download_model(model: &str) -> Result<PathBuf, String> {
    let target = model_path(model);
    if target.is_file() {
        return Ok(target);
    }
    let folder = whisper_dir();
    std::fs::create_dir_all(&folder)
        .map_err(|error| format!("could not create {}: {error}", folder.display()))?;

    let url = format!("{MODEL_BASE_URL}/{}", model_file(model));
    let agent = ureq::Agent::config_builder()
        .timeout_global(Some(std::time::Duration::from_secs(60 * 30)))
        .build()
        .new_agent();
    let mut response = agent
        .get(&url)
        .header("User-Agent", "Poratake")
        .call()
        .map_err(|error| format!("the model could not be downloaded: {error}"))?;
    if !(200..300).contains(&response.status().as_u16()) {
        return Err(format!(
            "the model could not be downloaded: {}",
            response.status()
        ));
    }

    // The file is written under a temporary name so an interrupted download
    // never leaves a half-written model that later looks installed.
    let partial = folder.join(format!("{}.part", model_file(model)));
    let mut file = std::fs::File::create(&partial)
        .map_err(|error| format!("could not write the model: {error}"))?;
    std::io::copy(&mut response.body_mut().as_reader(), &mut file)
        .map_err(|error| format!("could not write the model: {error}"))?;
    drop(file);
    std::fs::rename(&partial, &target)
        .map_err(|error| format!("could not save the model: {error}"))?;
    Ok(target)
}

/// `parseSrtTimestamp` — `HH:MM:SS,mmm`.
pub fn parse_srt_timestamp(value: &str) -> Option<f64> {
    let (clock, millis) = value.trim().split_once(',')?;
    let parts: Vec<&str> = clock.split(':').collect();
    if parts.len() != 3 {
        return None;
    }
    let hours: f64 = parts[0].parse().ok()?;
    let minutes: f64 = parts[1].parse().ok()?;
    let seconds: f64 = parts[2].parse().ok()?;
    let millis: f64 = millis.parse().ok()?;
    Some(hours * 3600.0 + minutes * 60.0 + seconds + millis / 1000.0)
}

/// `parseSrtToSubtitleData`.
pub fn parse_srt(content: &str) -> SubtitleData {
    let mut segments = Vec::new();
    for block in content.trim().split("\n\n") {
        let lines: Vec<&str> = block.lines().map(str::trim_end).collect();
        if lines.len() < 3 {
            continue;
        }
        let Some((from, to)) = lines[1].split_once("-->") else {
            continue;
        };
        let (Some(start), Some(end)) = (parse_srt_timestamp(from), parse_srt_timestamp(to)) else {
            continue;
        };
        segments.push(SubtitleSegment {
            start,
            end,
            text: lines[2..].join(" ").trim().to_string(),
            words: None,
        });
    }

    SubtitleData {
        segments,
        meta: SubtitleMeta {
            generated_at: chrono::Utc::now().to_rfc3339(),
            language: "en".to_string(),
            model: "imported".to_string(),
            prompt: None,
        },
    }
}

/// Reads a `.json` or `.srt` transcript and writes it as the project's
/// `subtitle.json`.
pub fn import_from(project: &Path, source: &Path) -> Result<SubtitleData, String> {
    let content = std::fs::read_to_string(source)
        .map_err(|error| format!("could not read {}: {error}", source.display()))?;

    let data: SubtitleData = if source
        .extension()
        .is_some_and(|extension| extension.eq_ignore_ascii_case("srt"))
    {
        parse_srt(&content)
    } else {
        serde_json::from_str(&content)
            .map_err(|error| format!("the file is not a transcript: {error}"))?
    };

    if data.segments.is_empty() {
        return Err("The file has no subtitle segments".to_string());
    }

    let path = crate::video::project::subtitle_path(project);
    let serialized = serde_json::to_string_pretty(&data)
        .map_err(|error| format!("the transcript could not be saved: {error}"))?;
    std::fs::write(&path, serialized)
        .map_err(|error| format!("the transcript could not be saved: {error}"))?;
    Ok(data)
}

/// Removes the project's transcript.
pub fn delete(project: &Path) {
    let path = crate::video::project::subtitle_path(project);
    let _ = std::fs::remove_file(path);
}

#[derive(Clone, Debug)]
pub struct Options {
    pub model: String,
    pub language: String,
    pub prompt: Option<String>,
}

impl Default for Options {
    fn default() -> Self {
        Self {
            model: "base".to_string(),
            language: "auto".to_string(),
            prompt: None,
        }
    }
}

/// Transcribes the project's audio, writing `subtitle.json` next to it.
/// Blocking, so callers run it on the background executor.
pub fn transcribe(project: &Path, options: &Options) -> Result<SubtitleData, String> {
    let cli = cli_path();
    if !cli.is_file() {
        return Err("Whisper binary not found".to_string());
    }
    let model = model_path(&options.model);
    if !model.is_file() {
        return Err(format!("Model {} not found", options.model));
    }

    let samples = audio_for(project).ok_or_else(|| "Audio file not found".to_string())?;
    let mono = to_whisper_pcm(&samples, crate::video::encoder::AUDIO_SAMPLE_RATE);
    if mono.is_empty() {
        return Err("The recording has no audio to transcribe".to_string());
    }

    let folder = crate::video::project::project_folder(project).unwrap_or_else(std::env::temp_dir);
    let wav_path = folder.join("temp_transcribe.wav");
    let json_stem = folder.join("temp_transcribe");
    let json_path = folder.join("temp_transcribe.json");

    std::fs::write(&wav_path, wav_bytes(&mono, WHISPER_SAMPLE_RATE))
        .map_err(|error| format!("could not write the audio: {error}"))?;

    let result = run_whisper(&cli, &model, &wav_path, &json_stem, options);
    let _ = std::fs::remove_file(&wav_path);

    result?;

    let contents = std::fs::read_to_string(&json_path)
        .map_err(|_| "Whisper produced no transcript".to_string())?;
    let _ = std::fs::remove_file(&json_path);

    let parsed: serde_json::Value = serde_json::from_str(&contents)
        .map_err(|error| format!("the transcript could not be parsed: {error}"))?;
    let segments = parse_output(&parsed);
    if segments.is_empty() {
        return Err("No speech was found in this recording".to_string());
    }

    let data = SubtitleData {
        segments,
        meta: SubtitleMeta {
            generated_at: chrono::Utc::now().to_rfc3339(),
            language: options.language.clone(),
            model: options.model.clone(),
            prompt: options.prompt.clone(),
        },
    };

    let path = crate::video::project::subtitle_path(project);
    let serialized = serde_json::to_string_pretty(&data)
        .map_err(|error| format!("the transcript could not be saved: {error}"))?;
    std::fs::write(&path, serialized)
        .map_err(|error| format!("the transcript could not be saved: {error}"))?;

    Ok(data)
}

/// The microphone track is the one worth transcribing; system audio is the
/// fallback when a recording has no microphone.
fn audio_for(project: &Path) -> Option<Vec<i16>> {
    let mic = crate::video::project::mic_audio_path(project);
    if let Some(samples) = crate::video::audio::decode(&mic) {
        return Some(samples);
    }
    let system = crate::video::project::system_audio_path(project);
    crate::video::audio::decode(&system)
}

fn run_whisper(
    cli: &Path,
    model: &Path,
    wav: &Path,
    json_stem: &Path,
    options: &Options,
) -> Result<(), String> {
    let base_args: Vec<String> = vec![
        "-m".into(),
        model.to_string_lossy().to_string(),
        "-f".into(),
        wav.to_string_lossy().to_string(),
        "-ojf".into(),
        "-of".into(),
        json_stem.to_string_lossy().to_string(),
        "-ml".into(),
        "60".into(),
        "-sow".into(),
        "-nfa".into(),
        "-dtw".into(),
        dtw_preset(&options.model).to_string(),
    ];

    let mut args = base_args.clone();
    if let Some(prompt) = options
        .prompt
        .as_ref()
        .filter(|value| !value.trim().is_empty())
    {
        args.push("--prompt".into());
        args.push(prompt.clone());
    }

    let output = std::process::Command::new(cli)
        .args(&args)
        .output()
        .map_err(|error| format!("Whisper could not be started: {error}"))?;
    if output.status.success() {
        return Ok(());
    }

    // Builds without DTW support reject `-dtw`; drop it and use the plain JSON
    // output, exactly as the Electron path falls back.
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    if !is_dtw_unsupported(&stderr) {
        return Err(format!("Whisper failed: {}", stderr.trim()));
    }

    let mut fallback: Vec<String> = Vec::new();
    let mut skip_next = false;
    for argument in &args {
        if skip_next {
            skip_next = false;
            continue;
        }
        if argument == "-dtw" {
            skip_next = true;
            continue;
        }
        fallback.push(if argument == "-ojf" {
            "-oj".to_string()
        } else {
            argument.clone()
        });
    }

    let output = std::process::Command::new(cli)
        .args(&fallback)
        .output()
        .map_err(|error| format!("Whisper could not be started: {error}"))?;
    if output.status.success() {
        return Ok(());
    }
    Err(format!(
        "Whisper failed: {}",
        String::from_utf8_lossy(&output.stderr).trim()
    ))
}

fn is_dtw_unsupported(stderr: &str) -> bool {
    let lowered = stderr.to_lowercase();
    lowered.contains("dtw") && (lowered.contains("unsupported") || lowered.contains("unknown"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn model_files_follow_the_whisper_cpp_names() {
        assert_eq!(model_file("base"), "ggml-base.bin");
        assert_eq!(model_file("small"), "ggml-small.bin");
        assert_eq!(model_file("medium"), "ggml-medium.bin");
        assert_eq!(model_file("nonsense"), "ggml-base.bin");
    }

    #[test]
    fn timestamps_parse_with_and_without_millis() {
        assert_eq!(parse_timestamp("00:00:01.500"), Some(1.5));
        assert_eq!(parse_timestamp("01:02:03"), Some(3723.0));
        assert_eq!(parse_timestamp("00:00:01,25"), Some(1.25));
        assert_eq!(parse_timestamp("nope"), None);
    }

    #[test]
    fn offsets_win_over_timestamps() {
        let json = serde_json::json!({
            "transcription": [{
                "timestamps": { "from": "00:00:09.000", "to": "00:00:10.000" },
                "offsets": { "from": 1000, "to": 2000 },
                "text": " Hello there "
            }]
        });
        let segments = parse_output(&json);
        assert_eq!(segments.len(), 1);
        assert_eq!(segments[0].start, 1.0);
        assert_eq!(segments[0].end, 2.0);
        assert_eq!(segments[0].text, "Hello there");
    }

    #[test]
    fn tokens_are_joined_into_words_on_their_leading_space() {
        let json = serde_json::json!({
            "transcription": [{
                "timestamps": { "from": "00:00:00.000", "to": "00:00:02.000" },
                "offsets": { "from": 0, "to": 2000 },
                "text": "hello world",
                "tokens": [
                    { "text": "[_BEG_]", "offsets": { "from": 0, "to": 0 } },
                    { "text": "hel", "offsets": { "from": 0, "to": 300 } },
                    { "text": "lo", "offsets": { "from": 300, "to": 600 } },
                    { "text": " wor", "offsets": { "from": 700, "to": 1200 } },
                    { "text": "ld", "offsets": { "from": 1200, "to": 1600 } }
                ]
            }]
        });
        let words = parse_output(&json)[0].words.clone().expect("words");
        assert_eq!(words.len(), 2);
        assert_eq!(words[0].text, "hello");
        assert_eq!(words[0].start, 0.0);
        assert_eq!(words[0].end, 0.6);
        assert_eq!(words[1].text, "world");
        assert_eq!(words[1].start, 0.7);
    }

    #[test]
    fn a_segment_without_tokens_has_no_word_timings() {
        let json = serde_json::json!({
            "transcription": [{
                "timestamps": { "from": "00:00:00.000", "to": "00:00:01.000" },
                "text": "hi"
            }]
        });
        assert!(parse_output(&json)[0].words.is_none());
    }

    #[test]
    fn a_malformed_transcript_yields_no_segments() {
        assert!(parse_output(&serde_json::json!({})).is_empty());
        assert!(parse_output(&serde_json::json!({ "transcription": 5 })).is_empty());
    }

    #[test]
    fn resampling_downmixes_and_shortens_the_buffer() {
        // One second of 48 kHz stereo becomes one second of 16 kHz mono.
        let samples: Vec<i16> = (0..48_000).flat_map(|_| [1000i16, 2000]).collect();
        let mono = to_whisper_pcm(&samples, 48_000);
        assert_eq!(mono.len(), 16_000);
        assert!(mono.iter().all(|value| (1400..=1600).contains(value)));
    }

    #[test]
    fn an_empty_buffer_resamples_to_nothing() {
        assert!(to_whisper_pcm(&[], 48_000).is_empty());
        assert!(to_whisper_pcm(&[1, 2], 0).is_empty());
    }

    #[test]
    fn the_wav_header_describes_mono_sixteen_bit() {
        let wav = wav_bytes(&[0, 1, -1], WHISPER_SAMPLE_RATE);
        assert_eq!(&wav[0..4], b"RIFF");
        assert_eq!(&wav[8..12], b"WAVE");
        assert_eq!(u16::from_le_bytes([wav[22], wav[23]]), 1);
        assert_eq!(
            u32::from_le_bytes([wav[24], wav[25], wav[26], wav[27]]),
            WHISPER_SAMPLE_RATE
        );
        assert_eq!(u16::from_le_bytes([wav[34], wav[35]]), 16);
        assert_eq!(wav.len(), 44 + 6);
    }

    #[test]
    fn a_dtw_rejection_is_recognized() {
        assert!(is_dtw_unsupported("error: unknown argument -dtw"));
        assert!(is_dtw_unsupported("DTW is unsupported in this build"));
        assert!(!is_dtw_unsupported("failed to load model"));
    }

    #[test]
    fn srt_timestamps_parse_to_seconds() {
        assert_eq!(parse_srt_timestamp("00:00:01,500"), Some(1.5));
        assert_eq!(parse_srt_timestamp(" 01:02:03,000 "), Some(3723.0));
        assert_eq!(parse_srt_timestamp("00:00:01.500"), None);
    }

    #[test]
    fn an_srt_file_becomes_subtitle_segments() {
        let content = "1\n00:00:00,000 --> 00:00:02,000\nHello there\n\n2\n00:00:02,500 --> 00:00:04,000\nSecond line\nwrapped";
        let data = parse_srt(content);
        assert_eq!(data.segments.len(), 2);
        assert_eq!(data.segments[0].text, "Hello there");
        assert_eq!(data.segments[1].start, 2.5);
        assert_eq!(data.segments[1].text, "Second line wrapped");
        assert_eq!(data.meta.model, "imported");
    }

    #[test]
    fn malformed_srt_blocks_are_skipped() {
        let data = parse_srt("1\nnot a timestamp\ntext\n\n2\n00:00:01,000 --> 00:00:02,000\nok");
        assert_eq!(data.segments.len(), 1);
        assert_eq!(data.segments[0].text, "ok");
    }

    #[test]
    fn importing_an_empty_transcript_is_refused() {
        let source = std::env::temp_dir().join("poratake-empty.srt");
        std::fs::write(&source, "").expect("write");
        let error = import_from(&std::env::temp_dir(), &source).unwrap_err();
        assert!(error.contains("no subtitle segments"), "{error}");
        let _ = std::fs::remove_file(&source);
    }
}
